sudo: false

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: hhvm
  allow_failures:
    - php: hhvm

before_install:
  - composer self-update

install:
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]]; then yes '' | pecl -q install -f mongo-1.5.8; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then pecl install -f mongodb-stable; fi
  - travis_retry composer install --no-interaction --ignore-platform-reqs --prefer-source
  - composer info -i

script:
  - composer test
  - composer cs

notifications:
  email: true
