sudo: false

language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: hhvm
  allow_failures:
    - php: hhvm

before_install:
  - pecl install -f mongodb-stable
  - composer config "platform.ext-mongo" "1.6.16"
  - composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-source
  - composer info -i

script:
  - composer test
  - composer cs

notifications:
  email: true
